<?php
/**
 * Xtream UI Pro - provisioning logic (create / renew / suspend / unsuspend /
 * terminate) for an IPTV line and for a sub-reseller account.
 *
 * PART OF THE PLATFORM-INDEPENDENT CORE: no ClientExec class is used here.
 * The ClientExec plugin (PluginXtreampro.php) only translates ClientExec
 * events into calls on this class and stores what it returns.
 *
 * A "service" is the array the caller passes in:
 *   id          stable id of the service on the billing side (ClientExec package id)
 *   generation  how many times the service was terminated (see below)
 *   remote_id   panel id of the line / sub-reseller; '' when not created yet
 *   username    username on the service (may be '')
 *   password    password on the service (may be '')
 *
 * Request ids make create / renew / credit transfers idempotent in the panel:
 * the same request id returns the first result instead of charging again.
 * They are built from the service id and its "generation". The generation is
 * raised by terminate(), so creating a terminated service again sells a NEW
 * line instead of replaying the deleted one.
 *
 * @version 1.1.0
 */

namespace XtreamPro\ClientExec;

require_once __DIR__ . '/Client.php';

class Provisioner
{
    const KIND_LINE = 'line';
    const KIND_RESELLER = 'reseller';

    /** @var Client */
    private $client;

    public function __construct(Client $client)
    {
        $this->client = $client;
    }

    /** "line" unless the product says "reseller" (an unknown value is a line). */
    public static function kindOf($serviceType)
    {
        return strtolower(trim((string) $serviceType)) === self::KIND_RESELLER ? self::KIND_RESELLER : self::KIND_LINE;
    }

    // ---- create ------------------------------------------------------------

    /**
     * Create the line. Returns array(remote_id, username, password): the
     * credentials the panel really used (the reseller's group may ignore the
     * ones sent, and blank ones are generated by the panel).
     *
     * @param callable|null $persist  called with the result as soon as the line exists
     */
    public function createLine(array $service, $packageId, $trial, $persist = null)
    {
        $packageId = (int) $packageId;
        if ($packageId <= 0) {
            throw new \RuntimeException('No panel package id is set in the package settings of the product.');
        }

        // Ask the panel first: too few credits, a package that is not on sale or one for boxes only fail here
        // with the amounts and nothing is created.
        $this->client->assertCanSellPackage($packageId, (bool) $trial, true);

        $data = $this->client->createLine(
            $packageId,
            (bool) $trial,
            self::text($service, 'username'),
            self::text($service, 'password'),
            'clientexec-create-' . $service['id'] . '-' . self::generation($service)
        );

        $line = (is_array($data) && isset($data['line']) && is_array($data['line'])) ? $data['line'] : array();
        if (!isset($line['id'])) {
            throw new ApiException('BAD_RESPONSE');
        }
        $password = isset($line['password']) ? (string) $line['password'] : '';
        if ($password === '' && isset($data['password'])) {
            $password = (string) $data['password'];
        }
        $result = array(
            'remote_id' => (string) (int) $line['id'],
            'username'  => isset($line['username']) ? (string) $line['username'] : '',
            'password'  => $password,
        );
        if ($persist !== null) {
            call_user_func($persist, $result);
        }
        return $result;
    }

    /**
     * Create the sub-reseller account, then hand over the starting credits.
     * Returns array(remote_id, username, password).
     *
     * The credentials are generated here when the service has none, and handed
     * to $persist BEFORE the panel is called: the panel stores only a hash, so
     * a repeated call (timeout, failed credit transfer) must send the very same
     * values. $persist is called a second time once the account exists. If the
     * credit transfer fails the account stays and the error is thrown; running
     * create again repeats only the transfer (same request id, charged once).
     *
     * @param callable|null $persist
     */
    public function createSubReseller(array $service, $email, $fullname, $creditsOnCreate, $persist = null)
    {
        $creditsOnCreate = self::credits($creditsOnCreate, 'Credits on creation');
        $generation = self::generation($service);
        if (self::text($service, 'remote_id') === '') {
            // The price of the account plus the credits to hand over: checked before the account exists.
            $this->client->assertCanCreateSubUser($creditsOnCreate);
        }

        $username = trim(self::text($service, 'username'));
        if ($username === '') {
            $username = 'r' . $service['id'] . self::random(6, 'abcdefghijklmnopqrstuvwxyz');
        }
        // Panel rule: letters, digits, "_ . -", 3 to 32 characters. A longer name is cut.
        $username = substr($username, 0, 32);
        if (!preg_match('/^[A-Za-z0-9_.-]{3,32}$/', $username)) {
            throw new \RuntimeException('The username "' . $username . '" is not valid for a sub-reseller: use 3 to 32 letters, digits, "_", "." or "-".');
        }
        $password = self::text($service, 'password');
        if ($password === '') {
            $password = self::random(14, 'abcdefghijkmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789');
        }
        if ($persist !== null) {
            call_user_func($persist, array('remote_id' => '', 'username' => $username, 'password' => $password));
        }

        $data = $this->client->createSubUser(
            $username,
            $password,
            (string) $email,
            (string) $fullname,
            'clientexec-sub-' . $service['id'] . '-' . $generation
        );
        $user = (is_array($data) && isset($data['user']) && is_array($data['user'])) ? $data['user'] : array();
        if (!isset($user['id'])) {
            throw new ApiException('BAD_RESPONSE');
        }
        if (isset($user['username']) && $user['username'] !== '') {
            $username = (string) $user['username'];
        }
        if (isset($data['password']) && $data['password'] !== '') {
            $password = (string) $data['password'];
        }
        $result = array('remote_id' => (string) $user['id'], 'username' => $username, 'password' => $password);
        if ($persist !== null) {
            call_user_func($persist, $result);
        }

        if ($creditsOnCreate > 0) {
            $this->client->adjustCredits(
                $result['remote_id'],
                $creditsOnCreate,
                'ClientExec service #' . $service['id'],
                'clientexec-subc-' . $service['id'] . '-' . $generation
            );
        }
        return $result;
    }

    // ---- suspend / unsuspend -----------------------------------------------

    public function suspend($kind, array $service)
    {
        $this->setEnabled($kind, $service, false);
    }

    public function unsuspend($kind, array $service)
    {
        $this->setEnabled($kind, $service, true);
    }

    private function setEnabled($kind, array $service, $enabled)
    {
        $id = $this->requireRemoteId($kind, $service);
        if ($kind === self::KIND_RESELLER) {
            $this->client->subUserAction($enabled ? 'enable_user' : 'disable_user', $id);
        } else {
            $this->client->lineAction($enabled ? 'enable_line' : 'disable_line', $id);
        }
    }

    // ---- terminate -----------------------------------------------------------

    /**
     * Delete (or only disable) the line; disable the sub-reseller (the panel has
     * no delete for accounts). Something already gone from the panel counts as
     * terminated. Returns the NEW generation the caller must store: the service
     * can be created again afterwards and then sells a new line.
     *
     * @param bool $delete  line only: true = delete_line (final), false = disable_line
     */
    public function terminate($kind, array $service, $delete)
    {
        $id = $this->findRemoteId($kind, $service);
        if ($id !== null) {
            try {
                if ($kind === self::KIND_RESELLER) {
                    $this->client->subUserAction('disable_user', $id);
                } else {
                    $this->client->lineAction($delete ? 'delete_line' : 'disable_line', $id);
                }
            } catch (ApiException $e) {
                if ($e->getErrorCode() !== 'RESOURCE_NOT_FOUND') {
                    throw $e;
                }
            }
        }
        return self::generation($service) + 1;
    }

    // ---- renew ---------------------------------------------------------------

    /**
     * Line: renew_line (charged). Sub-reseller: hand over $creditsPerRenewal
     * credits (0 = nothing to do). $day (Ymd) is part of the request id, so a
     * repeat on the same day returns the first result instead of charging twice.
     *
     * $packageId: the panel package of the product; a line renewal checks with `pricing` that it is on sale and paid.
     *
     * @return bool false when there was nothing to do
     */
    public function renew($kind, array $service, $creditsPerRenewal, $day, $packageId = 0)
    {
        if ($kind === self::KIND_RESELLER) {
            $credits = self::credits($creditsPerRenewal, 'Credits per renewal');
            if ($credits <= 0) {
                return false;
            }
            $this->client->assertCanGiveCredits($credits);
            $this->client->adjustCredits(
                $this->requireRemoteId($kind, $service),
                $credits,
                'ClientExec renewal, service #' . $service['id'],
                'clientexec-subr-' . $service['id'] . '-' . self::generation($service) . '-' . $day
            );
            return true;
        }
        if ((int) $packageId > 0) {
            // Fails with the amounts when the balance cannot pay the period; nothing is sold then.
            $this->client->assertCanSellPackage((int) $packageId, false, false);
        }
        $this->client->renewLine(
            (int) $this->requireRemoteId($kind, $service),
            'clientexec-renew-' . $service['id'] . '-' . self::generation($service) . '-' . $day
        );
        return true;
    }

    // ---- change package ----------------------------------------------------------

    /**
     * Upgrade / downgrade of a line: sells the new package on it (`change_package`, charged). Asks the panel first
     * (`pricing`, `package_compatibility`): a package that is not on sale, one for boxes only or too few credits
     * fail before anything is sold. A line already on the package is left alone (a repeated call). A panel that
     * does not know `package_compatibility` is treated as before; the sale is then decided by the panel itself.
     *
     * @return array|null null when nothing was sold; else array('sentence' => what the change did to the time
     *                    left and what it cost, according to the panel's answer before the sale; '' without one)
     */
    public function changePackage(array $service, $newPackageId)
    {
        $newPackageId = (int) $newPackageId;
        if ($newPackageId <= 0) {
            throw new \RuntimeException('No panel package id is set in the package settings of the new product.');
        }
        $id = (int) $this->requireRemoteId(self::KIND_LINE, $service);
        $line = $this->client->getLine($id);
        if (is_array($line) && isset($line['package_id']) && (int) $line['package_id'] === $newPackageId) {
            return null;
        }
        $this->client->assertCanSellPackage($newPackageId, false, true);
        $compat = $this->client->packageCompatibility($id, $newPackageId);
        $sentence = '';
        if (is_array($compat)) {
            $sentence = Client::describeCompatibility($compat);
            if (empty($compat['can_afford'])) {
                throw new ApiException('INSUFFICIENT_CREDITS', 402, 'The change costs ' . (int) (isset($compat['price']) ? $compat['price'] : 0) . ' credits.');
            }
        }
        // One request id per line state: a retry of the same change is not charged twice.
        $exp = (is_array($line) && isset($line['exp_date'])) ? (int) $line['exp_date'] : 0;
        $this->client->changePackage($id, $newPackageId, 'clientexec-chg-' . $service['id'] . '-' . self::generation($service) . '-' . $newPackageId . '-' . $exp);
        return array('sentence' => $sentence);
    }

    // ---- read ----------------------------------------------------------------

    /**
     * Current panel data of the service, or null when it does not exist (any
     * more). Keys: status (active | disabled | ...), and for a line: expiry
     * (Unix time or 0), max_connections, links; for a sub-reseller: credits.
     */
    public function describe($kind, array $service)
    {
        $id = $this->findRemoteId($kind, $service);
        if ($id === null) {
            return null;
        }
        if ($kind === self::KIND_RESELLER) {
            $user = $this->client->findSubUser($id, self::text($service, 'username'));
            if ($user === null) {
                return null;
            }
            return array(
                'remote_id' => (string) $id,
                'status'    => isset($user['status']) ? (string) $user['status'] : '',
                'credits'   => isset($user['credits']) ? (string) $user['credits'] : '',
            );
        }
        try {
            $line = $this->client->getLine((int) $id);
        } catch (ApiException $e) {
            if ($e->getErrorCode() === 'RESOURCE_NOT_FOUND') {
                return null;
            }
            throw $e;
        }
        if (!is_array($line)) {
            return null;
        }
        return array(
            'remote_id'       => (string) $id,
            'status'          => isset($line['status']) ? (string) $line['status'] : '',
            'expiry'          => isset($line['exp_date']) ? (int) $line['exp_date'] : 0,
            'max_connections' => isset($line['max_connections']) ? (string) $line['max_connections'] : '',
            'links'           => (isset($line['links']) && is_array($line['links'])) ? $line['links'] : array(),
        );
    }

    // ---- helpers ---------------------------------------------------------------

    /** Remote id from the service, otherwise looked up by exact username. Null when not found. */
    public function findRemoteId($kind, array $service)
    {
        $id = trim(self::text($service, 'remote_id'));
        if ($id !== '') {
            return $id;
        }
        $username = trim(self::text($service, 'username'));
        if ($username === '') {
            return null;
        }
        if ($kind === self::KIND_RESELLER) {
            $row = $this->client->findSubUser(null, $username);
        } else {
            $row = $this->client->findLineByUsername($username);
        }
        return ($row !== null && isset($row['id'])) ? (string) $row['id'] : null;
    }

    private function requireRemoteId($kind, array $service)
    {
        $id = $this->findRemoteId($kind, $service);
        if ($id === null) {
            throw new ApiException('RESOURCE_NOT_FOUND');
        }
        return $id;
    }

    private static function generation(array $service)
    {
        return isset($service['generation']) ? max(0, (int) $service['generation']) : 0;
    }

    private static function text(array $service, $key)
    {
        return isset($service[$key]) ? (string) $service[$key] : '';
    }

    /** Whole number >= 0 from a text setting ('' = 0). */
    public static function credits($value, $label)
    {
        $value = trim((string) $value);
        if ($value === '') {
            return 0;
        }
        if (!ctype_digit($value) || strlen($value) > 9) {
            throw new \RuntimeException($label . ' in the package settings must be a whole number of 0 or more.');
        }
        return (int) $value;
    }

    /** Random string from a fixed alphabet, using random_int (CSPRNG). */
    private static function random($length, $alphabet)
    {
        $out = '';
        $max = strlen($alphabet) - 1;
        for ($i = 0; $i < $length; $i++) {
            $out .= $alphabet[random_int(0, $max)];
        }
        return $out;
    }
}
